# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startscreennoimg(1).ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from vragenlijstUI import Ui_Form as vragenlijstform

class Ui_Background(object):

    def openNewWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = vragenlijstform()
        self.ui.setupUi(self.window)
        self.window.activateWindow()
        self.window.show()

    def setupUi(self, Background):
        Background.setObjectName("Background")
        Background.setWindowModality(QtCore.Qt.NonModal)
        Background.resize(537, 430)
        Background.setAutoFillBackground(False)


        self.start_button = QtWidgets.QPushButton(Background)
        self.start_button.setGeometry(QtCore.QRect(210, 250, 111, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.start_button.setFont(font)
        self.start_button.setIconSize(QtCore.QSize(20, 20))
        self.start_button.setObjectName("start_button")
        self.label = QtWidgets.QLabel(Background)
        self.label.setGeometry(QtCore.QRect(120, 110, 291, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Background)
        QtCore.QMetaObject.connectSlotsByName(Background)

    def retranslateUi(self, Background):
        _translate = QtCore.QCoreApplication.translate
        Background.setWindowTitle(_translate("Background", "Dialog"))
        self.start_button.setText(_translate("Background", "START"))
        self.label.setText(_translate("Background", "De IT Soorteer Hoed"))
        self.start_button.clicked.connect(self.openNewWindow)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Background = QtWidgets.QWidget()
    ui = Ui_Background()
    ui.setupUi(Background)
    Background.show()
    sys.exit(app.exec_())
